gen_mocks:
	mockgen -source=./internal/services/invoice-storage.go \
	-destination=./internal/services/mocks/mock_invoice-storage.go

	mockgen -source=./internal/services/messages-dispatcher.go \
	-destination=./internal/services/mocks/mock_messages-dispatcher.go