gen:
	mockgen -source=./internal/services/invoice-storage.go \
	-destination=./internal/services/mocks/mock_invoice-storage.go

	mockgen -source=./internal/services/kafka-dispatcher.go \
	-destination=./internal/services/mocks/mock_kafka-dispatcher.go