global:
  scrape_interval: 5s

scrape_configs:
  - job_name: 'api-service'
    static_configs:
      - targets: [ 'api-service:9090' ]
  - job_name: 'message-scheduler-service'
    static_configs:
      - targets: [ 'message-scheduler-service:9090' ]
