// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: validation/storage.proto

package validation

import (
	types "go-invoice-service/common/protocol/proto/types"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetInvoiceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            *types.UUID            `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetInvoiceRequest) Reset() {
	*x = GetInvoiceRequest{}
	mi := &file_validation_storage_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetInvoiceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetInvoiceRequest) ProtoMessage() {}

func (x *GetInvoiceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_validation_storage_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetInvoiceRequest.ProtoReflect.Descriptor instead.
func (*GetInvoiceRequest) Descriptor() ([]byte, []int) {
	return file_validation_storage_proto_rawDescGZIP(), []int{0}
}

func (x *GetInvoiceRequest) GetId() *types.UUID {
	if x != nil {
		return x.Id
	}
	return nil
}

type GetInvoiceResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Invoice       *types.Invoice         `protobuf:"bytes,1,opt,name=invoice" json:"invoice,omitempty"`
	Status        *types.InvoiceStatus   `protobuf:"varint,2,opt,name=status,enum=protocol.types.InvoiceStatus" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetInvoiceResponse) Reset() {
	*x = GetInvoiceResponse{}
	mi := &file_validation_storage_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetInvoiceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetInvoiceResponse) ProtoMessage() {}

func (x *GetInvoiceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_validation_storage_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetInvoiceResponse.ProtoReflect.Descriptor instead.
func (*GetInvoiceResponse) Descriptor() ([]byte, []int) {
	return file_validation_storage_proto_rawDescGZIP(), []int{1}
}

func (x *GetInvoiceResponse) GetInvoice() *types.Invoice {
	if x != nil {
		return x.Invoice
	}
	return nil
}

func (x *GetInvoiceResponse) GetStatus() types.InvoiceStatus {
	if x != nil && x.Status != nil {
		return *x.Status
	}
	return types.InvoiceStatus(0)
}

type SetApprovedRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            *types.UUID            `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetApprovedRequest) Reset() {
	*x = SetApprovedRequest{}
	mi := &file_validation_storage_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetApprovedRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetApprovedRequest) ProtoMessage() {}

func (x *SetApprovedRequest) ProtoReflect() protoreflect.Message {
	mi := &file_validation_storage_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetApprovedRequest.ProtoReflect.Descriptor instead.
func (*SetApprovedRequest) Descriptor() ([]byte, []int) {
	return file_validation_storage_proto_rawDescGZIP(), []int{2}
}

func (x *SetApprovedRequest) GetId() *types.UUID {
	if x != nil {
		return x.Id
	}
	return nil
}

type SetRejectedRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            *types.UUID            `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetRejectedRequest) Reset() {
	*x = SetRejectedRequest{}
	mi := &file_validation_storage_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetRejectedRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetRejectedRequest) ProtoMessage() {}

func (x *SetRejectedRequest) ProtoReflect() protoreflect.Message {
	mi := &file_validation_storage_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetRejectedRequest.ProtoReflect.Descriptor instead.
func (*SetRejectedRequest) Descriptor() ([]byte, []int) {
	return file_validation_storage_proto_rawDescGZIP(), []int{3}
}

func (x *SetRejectedRequest) GetId() *types.UUID {
	if x != nil {
		return x.Id
	}
	return nil
}

var File_validation_storage_proto protoreflect.FileDescriptor

const file_validation_storage_proto_rawDesc = "" +
	"\n" +
	"\x18validation/storage.proto\x12\x1bprotocol.validation.storage\x1a\x1bgoogle/protobuf/empty.proto\x1a\x10types/uuid.proto\x1a\x13types/invoice.proto\"9\n" +
	"\x11GetInvoiceRequest\x12$\n" +
	"\x02id\x18\x01 \x01(\v2\x14.protocol.types.UUIDR\x02id\"~\n" +
	"\x12GetInvoiceResponse\x121\n" +
	"\ainvoice\x18\x01 \x01(\v2\x17.protocol.types.InvoiceR\ainvoice\x125\n" +
	"\x06status\x18\x02 \x01(\x0e2\x1d.protocol.types.InvoiceStatusR\x06status\":\n" +
	"\x12SetApprovedRequest\x12$\n" +
	"\x02id\x18\x01 \x01(\v2\x14.protocol.types.UUIDR\x02id\":\n" +
	"\x12SetRejectedRequest\x12$\n" +
	"\x02id\x18\x01 \x01(\v2\x14.protocol.types.UUIDR\x02id2\xa8\x02\n" +
	"\x0eInvoiceStorage\x12f\n" +
	"\x03Get\x12..protocol.validation.storage.GetInvoiceRequest\x1a/.protocol.validation.storage.GetInvoiceResponse\x12V\n" +
	"\vSetApproved\x12/.protocol.validation.storage.SetApprovedRequest\x1a\x16.google.protobuf.Empty\x12V\n" +
	"\vSetRejected\x12/.protocol.validation.storage.SetRejectedRequest\x1a\x16.google.protobuf.EmptyB5Z3go-invoice-service/common/protocol/proto/validationb\beditionsp\xe8\a"

var (
	file_validation_storage_proto_rawDescOnce sync.Once
	file_validation_storage_proto_rawDescData []byte
)

func file_validation_storage_proto_rawDescGZIP() []byte {
	file_validation_storage_proto_rawDescOnce.Do(func() {
		file_validation_storage_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_validation_storage_proto_rawDesc), len(file_validation_storage_proto_rawDesc)))
	})
	return file_validation_storage_proto_rawDescData
}

var file_validation_storage_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_validation_storage_proto_goTypes = []any{
	(*GetInvoiceRequest)(nil),  // 0: protocol.validation.storage.GetInvoiceRequest
	(*GetInvoiceResponse)(nil), // 1: protocol.validation.storage.GetInvoiceResponse
	(*SetApprovedRequest)(nil), // 2: protocol.validation.storage.SetApprovedRequest
	(*SetRejectedRequest)(nil), // 3: protocol.validation.storage.SetRejectedRequest
	(*types.UUID)(nil),         // 4: protocol.types.UUID
	(*types.Invoice)(nil),      // 5: protocol.types.Invoice
	(types.InvoiceStatus)(0),   // 6: protocol.types.InvoiceStatus
	(*emptypb.Empty)(nil),      // 7: google.protobuf.Empty
}
var file_validation_storage_proto_depIdxs = []int32{
	4, // 0: protocol.validation.storage.GetInvoiceRequest.id:type_name -> protocol.types.UUID
	5, // 1: protocol.validation.storage.GetInvoiceResponse.invoice:type_name -> protocol.types.Invoice
	6, // 2: protocol.validation.storage.GetInvoiceResponse.status:type_name -> protocol.types.InvoiceStatus
	4, // 3: protocol.validation.storage.SetApprovedRequest.id:type_name -> protocol.types.UUID
	4, // 4: protocol.validation.storage.SetRejectedRequest.id:type_name -> protocol.types.UUID
	0, // 5: protocol.validation.storage.InvoiceStorage.Get:input_type -> protocol.validation.storage.GetInvoiceRequest
	2, // 6: protocol.validation.storage.InvoiceStorage.SetApproved:input_type -> protocol.validation.storage.SetApprovedRequest
	3, // 7: protocol.validation.storage.InvoiceStorage.SetRejected:input_type -> protocol.validation.storage.SetRejectedRequest
	1, // 8: protocol.validation.storage.InvoiceStorage.Get:output_type -> protocol.validation.storage.GetInvoiceResponse
	7, // 9: protocol.validation.storage.InvoiceStorage.SetApproved:output_type -> google.protobuf.Empty
	7, // 10: protocol.validation.storage.InvoiceStorage.SetRejected:output_type -> google.protobuf.Empty
	8, // [8:11] is the sub-list for method output_type
	5, // [5:8] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_validation_storage_proto_init() }
func file_validation_storage_proto_init() {
	if File_validation_storage_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_validation_storage_proto_rawDesc), len(file_validation_storage_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_validation_storage_proto_goTypes,
		DependencyIndexes: file_validation_storage_proto_depIdxs,
		MessageInfos:      file_validation_storage_proto_msgTypes,
	}.Build()
	File_validation_storage_proto = out.File
	file_validation_storage_proto_goTypes = nil
	file_validation_storage_proto_depIdxs = nil
}
