// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: types/invoice.proto

package types

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type InvoiceStatus int32

const (
	InvoiceStatus_Pending  InvoiceStatus = 0
	InvoiceStatus_Approved InvoiceStatus = 1
	InvoiceStatus_Rejected InvoiceStatus = 2
)

// Enum value maps for InvoiceStatus.
var (
	InvoiceStatus_name = map[int32]string{
		0: "Pending",
		1: "Approved",
		2: "Rejected",
	}
	InvoiceStatus_value = map[string]int32{
		"Pending":  0,
		"Approved": 1,
		"Rejected": 2,
	}
)

func (x InvoiceStatus) Enum() *InvoiceStatus {
	p := new(InvoiceStatus)
	*p = x
	return p
}

func (x InvoiceStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (InvoiceStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_types_invoice_proto_enumTypes[0].Descriptor()
}

func (InvoiceStatus) Type() protoreflect.EnumType {
	return &file_types_invoice_proto_enumTypes[0]
}

func (x InvoiceStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use InvoiceStatus.Descriptor instead.
func (InvoiceStatus) EnumDescriptor() ([]byte, []int) {
	return file_types_invoice_proto_rawDescGZIP(), []int{0}
}

type Item struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Description   *string                `protobuf:"bytes,1,opt,name=description" json:"description,omitempty"`
	Quantity      *int32                 `protobuf:"varint,2,opt,name=quantity" json:"quantity,omitempty"`
	UnitPrice     *int64                 `protobuf:"varint,3,opt,name=unitPrice" json:"unitPrice,omitempty"`
	Total         *int64                 `protobuf:"varint,4,opt,name=total" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Item) Reset() {
	*x = Item{}
	mi := &file_types_invoice_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Item) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Item) ProtoMessage() {}

func (x *Item) ProtoReflect() protoreflect.Message {
	mi := &file_types_invoice_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Item.ProtoReflect.Descriptor instead.
func (*Item) Descriptor() ([]byte, []int) {
	return file_types_invoice_proto_rawDescGZIP(), []int{0}
}

func (x *Item) GetDescription() string {
	if x != nil && x.Description != nil {
		return *x.Description
	}
	return ""
}

func (x *Item) GetQuantity() int32 {
	if x != nil && x.Quantity != nil {
		return *x.Quantity
	}
	return 0
}

func (x *Item) GetUnitPrice() int64 {
	if x != nil && x.UnitPrice != nil {
		return *x.UnitPrice
	}
	return 0
}

func (x *Item) GetTotal() int64 {
	if x != nil && x.Total != nil {
		return *x.Total
	}
	return 0
}

type Invoice struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            *UUID                  `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	CustomerId    *UUID                  `protobuf:"bytes,2,opt,name=customerId" json:"customerId,omitempty"`
	Amount        *int64                 `protobuf:"varint,3,opt,name=amount" json:"amount,omitempty"`
	Currency      *string                `protobuf:"bytes,4,opt,name=currency" json:"currency,omitempty"`
	DueDate       *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=dueDate" json:"dueDate,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=createdAt" json:"createdAt,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=updatedAt" json:"updatedAt,omitempty"`
	Items         []*Item                `protobuf:"bytes,8,rep,name=items" json:"items,omitempty"`
	Notes         *string                `protobuf:"bytes,9,opt,name=notes" json:"notes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Invoice) Reset() {
	*x = Invoice{}
	mi := &file_types_invoice_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Invoice) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Invoice) ProtoMessage() {}

func (x *Invoice) ProtoReflect() protoreflect.Message {
	mi := &file_types_invoice_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Invoice.ProtoReflect.Descriptor instead.
func (*Invoice) Descriptor() ([]byte, []int) {
	return file_types_invoice_proto_rawDescGZIP(), []int{1}
}

func (x *Invoice) GetId() *UUID {
	if x != nil {
		return x.Id
	}
	return nil
}

func (x *Invoice) GetCustomerId() *UUID {
	if x != nil {
		return x.CustomerId
	}
	return nil
}

func (x *Invoice) GetAmount() int64 {
	if x != nil && x.Amount != nil {
		return *x.Amount
	}
	return 0
}

func (x *Invoice) GetCurrency() string {
	if x != nil && x.Currency != nil {
		return *x.Currency
	}
	return ""
}

func (x *Invoice) GetDueDate() *timestamppb.Timestamp {
	if x != nil {
		return x.DueDate
	}
	return nil
}

func (x *Invoice) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Invoice) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

func (x *Invoice) GetItems() []*Item {
	if x != nil {
		return x.Items
	}
	return nil
}

func (x *Invoice) GetNotes() string {
	if x != nil && x.Notes != nil {
		return *x.Notes
	}
	return ""
}

var File_types_invoice_proto protoreflect.FileDescriptor

const file_types_invoice_proto_rawDesc = "" +
	"\n" +
	"\x13types/invoice.proto\x12\x0eprotocol.types\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x10types/uuid.proto\"x\n" +
	"\x04Item\x12 \n" +
	"\vdescription\x18\x01 \x01(\tR\vdescription\x12\x1a\n" +
	"\bquantity\x18\x02 \x01(\x05R\bquantity\x12\x1c\n" +
	"\tunitPrice\x18\x03 \x01(\x03R\tunitPrice\x12\x14\n" +
	"\x05total\x18\x04 \x01(\x03R\x05total\"\x85\x03\n" +
	"\aInvoice\x12$\n" +
	"\x02id\x18\x01 \x01(\v2\x14.protocol.types.UUIDR\x02id\x124\n" +
	"\n" +
	"customerId\x18\x02 \x01(\v2\x14.protocol.types.UUIDR\n" +
	"customerId\x12\x16\n" +
	"\x06amount\x18\x03 \x01(\x03R\x06amount\x12\x1a\n" +
	"\bcurrency\x18\x04 \x01(\tR\bcurrency\x124\n" +
	"\adueDate\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\adueDate\x128\n" +
	"\tcreatedAt\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x128\n" +
	"\tupdatedAt\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\x12*\n" +
	"\x05items\x18\b \x03(\v2\x14.protocol.types.ItemR\x05items\x12\x14\n" +
	"\x05notes\x18\t \x01(\tR\x05notes*8\n" +
	"\rInvoiceStatus\x12\v\n" +
	"\aPending\x10\x00\x12\f\n" +
	"\bApproved\x10\x01\x12\f\n" +
	"\bRejected\x10\x02B0Z.go-invoice-service/common/protocol/proto/typesb\beditionsp\xe8\a"

var (
	file_types_invoice_proto_rawDescOnce sync.Once
	file_types_invoice_proto_rawDescData []byte
)

func file_types_invoice_proto_rawDescGZIP() []byte {
	file_types_invoice_proto_rawDescOnce.Do(func() {
		file_types_invoice_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_types_invoice_proto_rawDesc), len(file_types_invoice_proto_rawDesc)))
	})
	return file_types_invoice_proto_rawDescData
}

var file_types_invoice_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_types_invoice_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_types_invoice_proto_goTypes = []any{
	(InvoiceStatus)(0),            // 0: protocol.types.InvoiceStatus
	(*Item)(nil),                  // 1: protocol.types.Item
	(*Invoice)(nil),               // 2: protocol.types.Invoice
	(*UUID)(nil),                  // 3: protocol.types.UUID
	(*timestamppb.Timestamp)(nil), // 4: google.protobuf.Timestamp
}
var file_types_invoice_proto_depIdxs = []int32{
	3, // 0: protocol.types.Invoice.id:type_name -> protocol.types.UUID
	3, // 1: protocol.types.Invoice.customerId:type_name -> protocol.types.UUID
	4, // 2: protocol.types.Invoice.dueDate:type_name -> google.protobuf.Timestamp
	4, // 3: protocol.types.Invoice.createdAt:type_name -> google.protobuf.Timestamp
	4, // 4: protocol.types.Invoice.updatedAt:type_name -> google.protobuf.Timestamp
	1, // 5: protocol.types.Invoice.items:type_name -> protocol.types.Item
	6, // [6:6] is the sub-list for method output_type
	6, // [6:6] is the sub-list for method input_type
	6, // [6:6] is the sub-list for extension type_name
	6, // [6:6] is the sub-list for extension extendee
	0, // [0:6] is the sub-list for field type_name
}

func init() { file_types_invoice_proto_init() }
func file_types_invoice_proto_init() {
	if File_types_invoice_proto != nil {
		return
	}
	file_types_uuid_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_types_invoice_proto_rawDesc), len(file_types_invoice_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_types_invoice_proto_goTypes,
		DependencyIndexes: file_types_invoice_proto_depIdxs,
		EnumInfos:         file_types_invoice_proto_enumTypes,
		MessageInfos:      file_types_invoice_proto_msgTypes,
	}.Build()
	File_types_invoice_proto = out.File
	file_types_invoice_proto_goTypes = nil
	file_types_invoice_proto_depIdxs = nil
}
