// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: types/outbox-message.proto

package types

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type OutboxMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            *int64                 `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
	Topic         *string                `protobuf:"bytes,2,opt,name=topic" json:"topic,omitempty"`
	Payload       []byte                 `protobuf:"bytes,3,opt,name=payload" json:"payload,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OutboxMessage) Reset() {
	*x = OutboxMessage{}
	mi := &file_types_outbox_message_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OutboxMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OutboxMessage) ProtoMessage() {}

func (x *OutboxMessage) ProtoReflect() protoreflect.Message {
	mi := &file_types_outbox_message_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OutboxMessage.ProtoReflect.Descriptor instead.
func (*OutboxMessage) Descriptor() ([]byte, []int) {
	return file_types_outbox_message_proto_rawDescGZIP(), []int{0}
}

func (x *OutboxMessage) GetId() int64 {
	if x != nil && x.Id != nil {
		return *x.Id
	}
	return 0
}

func (x *OutboxMessage) GetTopic() string {
	if x != nil && x.Topic != nil {
		return *x.Topic
	}
	return ""
}

func (x *OutboxMessage) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

var File_types_outbox_message_proto protoreflect.FileDescriptor

const file_types_outbox_message_proto_rawDesc = "" +
	"\n" +
	"\x1atypes/outbox-message.proto\x12\x0eprotocol.types\"O\n" +
	"\rOutboxMessage\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x14\n" +
	"\x05topic\x18\x02 \x01(\tR\x05topic\x12\x18\n" +
	"\apayload\x18\x03 \x01(\fR\apayloadB0Z.go-invoice-service/common/protocol/proto/typesb\beditionsp\xe8\a"

var (
	file_types_outbox_message_proto_rawDescOnce sync.Once
	file_types_outbox_message_proto_rawDescData []byte
)

func file_types_outbox_message_proto_rawDescGZIP() []byte {
	file_types_outbox_message_proto_rawDescOnce.Do(func() {
		file_types_outbox_message_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_types_outbox_message_proto_rawDesc), len(file_types_outbox_message_proto_rawDesc)))
	})
	return file_types_outbox_message_proto_rawDescData
}

var file_types_outbox_message_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_types_outbox_message_proto_goTypes = []any{
	(*OutboxMessage)(nil), // 0: protocol.types.OutboxMessage
}
var file_types_outbox_message_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_types_outbox_message_proto_init() }
func file_types_outbox_message_proto_init() {
	if File_types_outbox_message_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_types_outbox_message_proto_rawDesc), len(file_types_outbox_message_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_types_outbox_message_proto_goTypes,
		DependencyIndexes: file_types_outbox_message_proto_depIdxs,
		MessageInfos:      file_types_outbox_message_proto_msgTypes,
	}.Build()
	File_types_outbox_message_proto = out.File
	file_types_outbox_message_proto_goTypes = nil
	file_types_outbox_message_proto_depIdxs = nil
}
