// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: messagescheduler/storage.proto

package messagescheduler

import (
	types "go-invoice-service/common/protocol/proto/types"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	durationpb "google.golang.org/protobuf/types/known/durationpb"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetMessagesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MaxCount      *int32                 `protobuf:"varint,1,opt,name=maxCount" json:"maxCount,omitempty"`
	RetryAfter    *durationpb.Duration   `protobuf:"bytes,2,opt,name=retryAfter" json:"retryAfter,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMessagesRequest) Reset() {
	*x = GetMessagesRequest{}
	mi := &file_messagescheduler_storage_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMessagesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMessagesRequest) ProtoMessage() {}

func (x *GetMessagesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_messagescheduler_storage_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMessagesRequest.ProtoReflect.Descriptor instead.
func (*GetMessagesRequest) Descriptor() ([]byte, []int) {
	return file_messagescheduler_storage_proto_rawDescGZIP(), []int{0}
}

func (x *GetMessagesRequest) GetMaxCount() int32 {
	if x != nil && x.MaxCount != nil {
		return *x.MaxCount
	}
	return 0
}

func (x *GetMessagesRequest) GetRetryAfter() *durationpb.Duration {
	if x != nil {
		return x.RetryAfter
	}
	return nil
}

type GetMessagesResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	OutboxMessages []*types.OutboxMessage `protobuf:"bytes,1,rep,name=outboxMessages" json:"outboxMessages,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *GetMessagesResponse) Reset() {
	*x = GetMessagesResponse{}
	mi := &file_messagescheduler_storage_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMessagesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMessagesResponse) ProtoMessage() {}

func (x *GetMessagesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_messagescheduler_storage_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMessagesResponse.ProtoReflect.Descriptor instead.
func (*GetMessagesResponse) Descriptor() ([]byte, []int) {
	return file_messagescheduler_storage_proto_rawDescGZIP(), []int{1}
}

func (x *GetMessagesResponse) GetOutboxMessages() []*types.OutboxMessage {
	if x != nil {
		return x.OutboxMessages
	}
	return nil
}

type DeleteMessageRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            *int64                 `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteMessageRequest) Reset() {
	*x = DeleteMessageRequest{}
	mi := &file_messagescheduler_storage_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteMessageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteMessageRequest) ProtoMessage() {}

func (x *DeleteMessageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_messagescheduler_storage_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteMessageRequest.ProtoReflect.Descriptor instead.
func (*DeleteMessageRequest) Descriptor() ([]byte, []int) {
	return file_messagescheduler_storage_proto_rawDescGZIP(), []int{2}
}

func (x *DeleteMessageRequest) GetId() int64 {
	if x != nil && x.Id != nil {
		return *x.Id
	}
	return 0
}

var File_messagescheduler_storage_proto protoreflect.FileDescriptor

const file_messagescheduler_storage_proto_rawDesc = "" +
	"\n" +
	"\x1emessagescheduler/storage.proto\x12#protocol.messages_scheduler.storage\x1a\x1egoogle/protobuf/duration.proto\x1a\x1bgoogle/protobuf/empty.proto\x1a\x1atypes/outbox-message.proto\"k\n" +
	"\x12GetMessagesRequest\x12\x1a\n" +
	"\bmaxCount\x18\x01 \x01(\x05R\bmaxCount\x129\n" +
	"\n" +
	"retryAfter\x18\x02 \x01(\v2\x19.google.protobuf.DurationR\n" +
	"retryAfter\"\\\n" +
	"\x13GetMessagesResponse\x12E\n" +
	"\x0eoutboxMessages\x18\x01 \x03(\v2\x1d.protocol.types.OutboxMessageR\x0eoutboxMessages\"&\n" +
	"\x14DeleteMessageRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id2\xe6\x01\n" +
	"\rOutboxStorage\x12x\n" +
	"\x03Get\x127.protocol.messages_scheduler.storage.GetMessagesRequest\x1a8.protocol.messages_scheduler.storage.GetMessagesResponse\x12[\n" +
	"\x06Delete\x129.protocol.messages_scheduler.storage.DeleteMessageRequest\x1a\x16.google.protobuf.EmptyB;Z9go-invoice-service/common/protocol/proto/messageschedulerb\beditionsp\xe8\a"

var (
	file_messagescheduler_storage_proto_rawDescOnce sync.Once
	file_messagescheduler_storage_proto_rawDescData []byte
)

func file_messagescheduler_storage_proto_rawDescGZIP() []byte {
	file_messagescheduler_storage_proto_rawDescOnce.Do(func() {
		file_messagescheduler_storage_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_messagescheduler_storage_proto_rawDesc), len(file_messagescheduler_storage_proto_rawDesc)))
	})
	return file_messagescheduler_storage_proto_rawDescData
}

var file_messagescheduler_storage_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_messagescheduler_storage_proto_goTypes = []any{
	(*GetMessagesRequest)(nil),   // 0: protocol.messages_scheduler.storage.GetMessagesRequest
	(*GetMessagesResponse)(nil),  // 1: protocol.messages_scheduler.storage.GetMessagesResponse
	(*DeleteMessageRequest)(nil), // 2: protocol.messages_scheduler.storage.DeleteMessageRequest
	(*durationpb.Duration)(nil),  // 3: google.protobuf.Duration
	(*types.OutboxMessage)(nil),  // 4: protocol.types.OutboxMessage
	(*emptypb.Empty)(nil),        // 5: google.protobuf.Empty
}
var file_messagescheduler_storage_proto_depIdxs = []int32{
	3, // 0: protocol.messages_scheduler.storage.GetMessagesRequest.retryAfter:type_name -> google.protobuf.Duration
	4, // 1: protocol.messages_scheduler.storage.GetMessagesResponse.outboxMessages:type_name -> protocol.types.OutboxMessage
	0, // 2: protocol.messages_scheduler.storage.OutboxStorage.Get:input_type -> protocol.messages_scheduler.storage.GetMessagesRequest
	2, // 3: protocol.messages_scheduler.storage.OutboxStorage.Delete:input_type -> protocol.messages_scheduler.storage.DeleteMessageRequest
	1, // 4: protocol.messages_scheduler.storage.OutboxStorage.Get:output_type -> protocol.messages_scheduler.storage.GetMessagesResponse
	5, // 5: protocol.messages_scheduler.storage.OutboxStorage.Delete:output_type -> google.protobuf.Empty
	4, // [4:6] is the sub-list for method output_type
	2, // [2:4] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_messagescheduler_storage_proto_init() }
func file_messagescheduler_storage_proto_init() {
	if File_messagescheduler_storage_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_messagescheduler_storage_proto_rawDesc), len(file_messagescheduler_storage_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_messagescheduler_storage_proto_goTypes,
		DependencyIndexes: file_messagescheduler_storage_proto_depIdxs,
		MessageInfos:      file_messagescheduler_storage_proto_msgTypes,
	}.Build()
	File_messagescheduler_storage_proto = out.File
	file_messagescheduler_storage_proto_goTypes = nil
	file_messagescheduler_storage_proto_depIdxs = nil
}
