// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: messagescheduler/storage.proto

package messagescheduler

import (
	types "go-invoice-service/common/protocol/proto/types"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	durationpb "google.golang.org/protobuf/types/known/durationpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type UploadRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MaxCount      *int32                 `protobuf:"varint,1,opt,name=maxCount" json:"maxCount,omitempty"`
	RetryAfter    *durationpb.Duration   `protobuf:"bytes,2,opt,name=retryAfter" json:"retryAfter,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UploadRequest) Reset() {
	*x = UploadRequest{}
	mi := &file_messagescheduler_storage_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UploadRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadRequest) ProtoMessage() {}

func (x *UploadRequest) ProtoReflect() protoreflect.Message {
	mi := &file_messagescheduler_storage_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadRequest.ProtoReflect.Descriptor instead.
func (*UploadRequest) Descriptor() ([]byte, []int) {
	return file_messagescheduler_storage_proto_rawDescGZIP(), []int{0}
}

func (x *UploadRequest) GetMaxCount() int32 {
	if x != nil && x.MaxCount != nil {
		return *x.MaxCount
	}
	return 0
}

func (x *UploadRequest) GetRetryAfter() *durationpb.Duration {
	if x != nil {
		return x.RetryAfter
	}
	return nil
}

type UploadResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	OutboxMessages []*types.OutboxMessage `protobuf:"bytes,1,rep,name=outboxMessages" json:"outboxMessages,omitempty"`
	Error          *string                `protobuf:"bytes,2,opt,name=error" json:"error,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *UploadResponse) Reset() {
	*x = UploadResponse{}
	mi := &file_messagescheduler_storage_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UploadResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadResponse) ProtoMessage() {}

func (x *UploadResponse) ProtoReflect() protoreflect.Message {
	mi := &file_messagescheduler_storage_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadResponse.ProtoReflect.Descriptor instead.
func (*UploadResponse) Descriptor() ([]byte, []int) {
	return file_messagescheduler_storage_proto_rawDescGZIP(), []int{1}
}

func (x *UploadResponse) GetOutboxMessages() []*types.OutboxMessage {
	if x != nil {
		return x.OutboxMessages
	}
	return nil
}

func (x *UploadResponse) GetError() string {
	if x != nil && x.Error != nil {
		return *x.Error
	}
	return ""
}

var File_messagescheduler_storage_proto protoreflect.FileDescriptor

const file_messagescheduler_storage_proto_rawDesc = "" +
	"\n" +
	"\x1emessagescheduler/storage.proto\x12#protocol.messages_scheduler.storage\x1a\x1egoogle/protobuf/duration.proto\x1a\x1atypes/outbox-message.proto\"f\n" +
	"\rUploadRequest\x12\x1a\n" +
	"\bmaxCount\x18\x01 \x01(\x05R\bmaxCount\x129\n" +
	"\n" +
	"retryAfter\x18\x02 \x01(\v2\x19.google.protobuf.DurationR\n" +
	"retryAfter\"m\n" +
	"\x0eUploadResponse\x12E\n" +
	"\x0eoutboxMessages\x18\x01 \x03(\v2\x1d.protocol.types.OutboxMessageR\x0eoutboxMessages\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error2\x83\x01\n" +
	"\x0eInvoiceStorage\x12q\n" +
	"\x06Upload\x122.protocol.messages_scheduler.storage.UploadRequest\x1a3.protocol.messages_scheduler.storage.UploadResponseB;Z9go-invoice-service/common/protocol/proto/messageschedulerb\beditionsp\xe8\a"

var (
	file_messagescheduler_storage_proto_rawDescOnce sync.Once
	file_messagescheduler_storage_proto_rawDescData []byte
)

func file_messagescheduler_storage_proto_rawDescGZIP() []byte {
	file_messagescheduler_storage_proto_rawDescOnce.Do(func() {
		file_messagescheduler_storage_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_messagescheduler_storage_proto_rawDesc), len(file_messagescheduler_storage_proto_rawDesc)))
	})
	return file_messagescheduler_storage_proto_rawDescData
}

var file_messagescheduler_storage_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_messagescheduler_storage_proto_goTypes = []any{
	(*UploadRequest)(nil),       // 0: protocol.messages_scheduler.storage.UploadRequest
	(*UploadResponse)(nil),      // 1: protocol.messages_scheduler.storage.UploadResponse
	(*durationpb.Duration)(nil), // 2: google.protobuf.Duration
	(*types.OutboxMessage)(nil), // 3: protocol.types.OutboxMessage
}
var file_messagescheduler_storage_proto_depIdxs = []int32{
	2, // 0: protocol.messages_scheduler.storage.UploadRequest.retryAfter:type_name -> google.protobuf.Duration
	3, // 1: protocol.messages_scheduler.storage.UploadResponse.outboxMessages:type_name -> protocol.types.OutboxMessage
	0, // 2: protocol.messages_scheduler.storage.InvoiceStorage.Upload:input_type -> protocol.messages_scheduler.storage.UploadRequest
	1, // 3: protocol.messages_scheduler.storage.InvoiceStorage.Upload:output_type -> protocol.messages_scheduler.storage.UploadResponse
	3, // [3:4] is the sub-list for method output_type
	2, // [2:3] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_messagescheduler_storage_proto_init() }
func file_messagescheduler_storage_proto_init() {
	if File_messagescheduler_storage_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_messagescheduler_storage_proto_rawDesc), len(file_messagescheduler_storage_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_messagescheduler_storage_proto_goTypes,
		DependencyIndexes: file_messagescheduler_storage_proto_depIdxs,
		MessageInfos:      file_messagescheduler_storage_proto_msgTypes,
	}.Build()
	File_messagescheduler_storage_proto = out.File
	file_messagescheduler_storage_proto_goTypes = nil
	file_messagescheduler_storage_proto_depIdxs = nil
}
