// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.29.3
// source: messagescheduler/storage.proto

package messagescheduler

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	InvoiceStorage_Upload_FullMethodName = "/protocol.messages_scheduler.storage.InvoiceStorage/Upload"
)

// InvoiceStorageClient is the client API for InvoiceStorage service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type InvoiceStorageClient interface {
	Upload(ctx context.Context, in *UploadRequest, opts ...grpc.CallOption) (*UploadResponse, error)
}

type invoiceStorageClient struct {
	cc grpc.ClientConnInterface
}

func NewInvoiceStorageClient(cc grpc.ClientConnInterface) InvoiceStorageClient {
	return &invoiceStorageClient{cc}
}

func (c *invoiceStorageClient) Upload(ctx context.Context, in *UploadRequest, opts ...grpc.CallOption) (*UploadResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UploadResponse)
	err := c.cc.Invoke(ctx, InvoiceStorage_Upload_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// InvoiceStorageServer is the server API for InvoiceStorage service.
// All implementations must embed UnimplementedInvoiceStorageServer
// for forward compatibility.
type InvoiceStorageServer interface {
	Upload(context.Context, *UploadRequest) (*UploadResponse, error)
	mustEmbedUnimplementedInvoiceStorageServer()
}

// UnimplementedInvoiceStorageServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedInvoiceStorageServer struct{}

func (UnimplementedInvoiceStorageServer) Upload(context.Context, *UploadRequest) (*UploadResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Upload not implemented")
}
func (UnimplementedInvoiceStorageServer) mustEmbedUnimplementedInvoiceStorageServer() {}
func (UnimplementedInvoiceStorageServer) testEmbeddedByValue()                        {}

// UnsafeInvoiceStorageServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to InvoiceStorageServer will
// result in compilation errors.
type UnsafeInvoiceStorageServer interface {
	mustEmbedUnimplementedInvoiceStorageServer()
}

func RegisterInvoiceStorageServer(s grpc.ServiceRegistrar, srv InvoiceStorageServer) {
	// If the following call pancis, it indicates UnimplementedInvoiceStorageServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&InvoiceStorage_ServiceDesc, srv)
}

func _InvoiceStorage_Upload_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UploadRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InvoiceStorageServer).Upload(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: InvoiceStorage_Upload_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InvoiceStorageServer).Upload(ctx, req.(*UploadRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// InvoiceStorage_ServiceDesc is the grpc.ServiceDesc for InvoiceStorage service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var InvoiceStorage_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "protocol.messages_scheduler.storage.InvoiceStorage",
	HandlerType: (*InvoiceStorageServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Upload",
			Handler:    _InvoiceStorage_Upload_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "messagescheduler/storage.proto",
}
