// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.29.3
// source: messagescheduler/storage.proto

package messagescheduler

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	OutboxStorage_Get_FullMethodName    = "/protocol.messages_scheduler.storage.OutboxStorage/Get"
	OutboxStorage_Delete_FullMethodName = "/protocol.messages_scheduler.storage.OutboxStorage/Delete"
)

// OutboxStorageClient is the client API for OutboxStorage service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type OutboxStorageClient interface {
	Get(ctx context.Context, in *GetMessagesRequest, opts ...grpc.CallOption) (*GetMessagesResponse, error)
	Delete(ctx context.Context, in *DeleteMessageRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
}

type outboxStorageClient struct {
	cc grpc.ClientConnInterface
}

func NewOutboxStorageClient(cc grpc.ClientConnInterface) OutboxStorageClient {
	return &outboxStorageClient{cc}
}

func (c *outboxStorageClient) Get(ctx context.Context, in *GetMessagesRequest, opts ...grpc.CallOption) (*GetMessagesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetMessagesResponse)
	err := c.cc.Invoke(ctx, OutboxStorage_Get_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *outboxStorageClient) Delete(ctx context.Context, in *DeleteMessageRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, OutboxStorage_Delete_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// OutboxStorageServer is the server API for OutboxStorage service.
// All implementations must embed UnimplementedOutboxStorageServer
// for forward compatibility.
type OutboxStorageServer interface {
	Get(context.Context, *GetMessagesRequest) (*GetMessagesResponse, error)
	Delete(context.Context, *DeleteMessageRequest) (*emptypb.Empty, error)
	mustEmbedUnimplementedOutboxStorageServer()
}

// UnimplementedOutboxStorageServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedOutboxStorageServer struct{}

func (UnimplementedOutboxStorageServer) Get(context.Context, *GetMessagesRequest) (*GetMessagesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Get not implemented")
}
func (UnimplementedOutboxStorageServer) Delete(context.Context, *DeleteMessageRequest) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Delete not implemented")
}
func (UnimplementedOutboxStorageServer) mustEmbedUnimplementedOutboxStorageServer() {}
func (UnimplementedOutboxStorageServer) testEmbeddedByValue()                       {}

// UnsafeOutboxStorageServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to OutboxStorageServer will
// result in compilation errors.
type UnsafeOutboxStorageServer interface {
	mustEmbedUnimplementedOutboxStorageServer()
}

func RegisterOutboxStorageServer(s grpc.ServiceRegistrar, srv OutboxStorageServer) {
	// If the following call pancis, it indicates UnimplementedOutboxStorageServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&OutboxStorage_ServiceDesc, srv)
}

func _OutboxStorage_Get_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetMessagesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OutboxStorageServer).Get(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OutboxStorage_Get_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OutboxStorageServer).Get(ctx, req.(*GetMessagesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OutboxStorage_Delete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteMessageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OutboxStorageServer).Delete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OutboxStorage_Delete_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OutboxStorageServer).Delete(ctx, req.(*DeleteMessageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// OutboxStorage_ServiceDesc is the grpc.ServiceDesc for OutboxStorage service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var OutboxStorage_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "protocol.messages_scheduler.storage.OutboxStorage",
	HandlerType: (*OutboxStorageServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Get",
			Handler:    _OutboxStorage_Get_Handler,
		},
		{
			MethodName: "Delete",
			Handler:    _OutboxStorage_Delete_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "messagescheduler/storage.proto",
}
