// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: apiservice/storage/storage.proto

package storage

import (
	types "go-invoice-service/common/protocol/proto/types"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type UploadRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Invoice       *types.Invoice         `protobuf:"bytes,1,opt,name=invoice" json:"invoice,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UploadRequest) Reset() {
	*x = UploadRequest{}
	mi := &file_apiservice_storage_storage_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UploadRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadRequest) ProtoMessage() {}

func (x *UploadRequest) ProtoReflect() protoreflect.Message {
	mi := &file_apiservice_storage_storage_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadRequest.ProtoReflect.Descriptor instead.
func (*UploadRequest) Descriptor() ([]byte, []int) {
	return file_apiservice_storage_storage_proto_rawDescGZIP(), []int{0}
}

func (x *UploadRequest) GetInvoice() *types.Invoice {
	if x != nil {
		return x.Invoice
	}
	return nil
}

type UploadResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Error         *string                `protobuf:"bytes,1,opt,name=error" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UploadResponse) Reset() {
	*x = UploadResponse{}
	mi := &file_apiservice_storage_storage_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UploadResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadResponse) ProtoMessage() {}

func (x *UploadResponse) ProtoReflect() protoreflect.Message {
	mi := &file_apiservice_storage_storage_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadResponse.ProtoReflect.Descriptor instead.
func (*UploadResponse) Descriptor() ([]byte, []int) {
	return file_apiservice_storage_storage_proto_rawDescGZIP(), []int{1}
}

func (x *UploadResponse) GetError() string {
	if x != nil && x.Error != nil {
		return *x.Error
	}
	return ""
}

var File_apiservice_storage_storage_proto protoreflect.FileDescriptor

const file_apiservice_storage_storage_proto_rawDesc = "" +
	"\n" +
	" apiservice/storage/storage.proto\x12\x1cprotocol.api_service.storage\x1a\x13types/invoice.proto\"B\n" +
	"\rUploadRequest\x121\n" +
	"\ainvoice\x18\x01 \x01(\v2\x17.protocol.types.InvoiceR\ainvoice\"&\n" +
	"\x0eUploadResponse\x12\x14\n" +
	"\x05error\x18\x01 \x01(\tR\x05error2u\n" +
	"\x0eInvoiceStorage\x12c\n" +
	"\x06Upload\x12+.protocol.api_service.storage.UploadRequest\x1a,.protocol.api_service.storage.UploadResponseB=Z;go-invoice-service/common/protocol/proto/apiservice/storageb\beditionsp\xe8\a"

var (
	file_apiservice_storage_storage_proto_rawDescOnce sync.Once
	file_apiservice_storage_storage_proto_rawDescData []byte
)

func file_apiservice_storage_storage_proto_rawDescGZIP() []byte {
	file_apiservice_storage_storage_proto_rawDescOnce.Do(func() {
		file_apiservice_storage_storage_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_apiservice_storage_storage_proto_rawDesc), len(file_apiservice_storage_storage_proto_rawDesc)))
	})
	return file_apiservice_storage_storage_proto_rawDescData
}

var file_apiservice_storage_storage_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_apiservice_storage_storage_proto_goTypes = []any{
	(*UploadRequest)(nil),  // 0: protocol.api_service.storage.UploadRequest
	(*UploadResponse)(nil), // 1: protocol.api_service.storage.UploadResponse
	(*types.Invoice)(nil),  // 2: protocol.types.Invoice
}
var file_apiservice_storage_storage_proto_depIdxs = []int32{
	2, // 0: protocol.api_service.storage.UploadRequest.invoice:type_name -> protocol.types.Invoice
	0, // 1: protocol.api_service.storage.InvoiceStorage.Upload:input_type -> protocol.api_service.storage.UploadRequest
	1, // 2: protocol.api_service.storage.InvoiceStorage.Upload:output_type -> protocol.api_service.storage.UploadResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_apiservice_storage_storage_proto_init() }
func file_apiservice_storage_storage_proto_init() {
	if File_apiservice_storage_storage_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_apiservice_storage_storage_proto_rawDesc), len(file_apiservice_storage_storage_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_apiservice_storage_storage_proto_goTypes,
		DependencyIndexes: file_apiservice_storage_storage_proto_depIdxs,
		MessageInfos:      file_apiservice_storage_storage_proto_msgTypes,
	}.Build()
	File_apiservice_storage_storage_proto = out.File
	file_apiservice_storage_storage_proto_goTypes = nil
	file_apiservice_storage_storage_proto_depIdxs = nil
}
